In [1]:
import torch
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X>Y)

a = torch.arange(3).reshape((3, 1))

c:\Users\20249\.conda\envs\test1\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])


关于广播机制

In [3]:
import torch
a = torch.arange(3).reshape((3, 1))
b = torch.arange(4).reshape((1, 4))
print(a)
print(b)
print(a+b)
print((a+b).shape)


tensor([[0],
        [1],
        [2]])
tensor([[0, 1, 2, 3]])
tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])
torch.Size([3, 4])
